version: "3.5"

services:
  node:
    build: ./node
    networks:
      hawking:
        ipv4_address: 172.28.0.2
    restart: on-failure
    stop_signal: SIGINT
    stop_grace_period: 10s
    ports:
      - 9944:9944
    expose:
      - 9944
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    command: bash -c "./node-template --dev --ws-external"

  front-end:
    build: ./front-end
    networks:
      hawking:
        ipv4_address: 172.28.0.3
    restart: on-failure
    stop_signal: SIGINT
    stop_grace_period: 10s
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - PROVIDER_SOCKET=ws://127.0.0.1:9944
      - ENVIROMENT=dev
    command: bash -c "./start.sh start"

volumes:
  node-data: {}

networks:
  hawking:
    name: hawking
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
